### PR TITLE
Upgrades to Bootstrap v5 removing all customization except colors

### PR DESCRIPTION
**Pull request by xezian**
I've upgraded this package to bootstrap 5 while also removing any customization that's about anything but color. I also added button variants for the `$colors` and `$theme-colors`

Also, I switched the logic in `_colors.scss`, where every `text-#{color}` would be overwritten for every background color, literally generating 10s of thousands of lines of css, and instead I'm just having it create each `text-#{color}` as !important after the backgrounds (it looks to me like this is what bootstrap is also doing for theme colors)

Bumped the version number to 1.4.0 because of the upgrade to Bootstrap 5

I was testing the buttons, and making sure the compiled css worked right by linking the locally compiled css `<link rel="stylesheet" href="../dist/bootstrap.css" />`, but they won't work if we use the massive file currently at "https://assets.cdn.fso.arizona.edu/fso-bootstrap/bootstrap.css", so after merging this I think I will want to switch the file in the s3 bucket to use the one created by this updated version.

### CODE REVIEW

**Comment by brxck** [comment]
> Also, I switched the logic in _colors.scss

What do we get out of taking over class generation in this file? Aren't we able to just customize the color variables and leave the rest to Bootstrap?

> Bumped the version number to 1.4.0 because of the upgrade to Bootstrap 5

If this isn't a major version change (2.0) then idk what is.

> If it were me, I'd just upload that page and CSS to a bucket in the deploy action.

**Comment by brxck** [comment]
> literally generating 10s of thousands of lines of css

This is hilarious, good catch! I checked and we're at 970kb vs 23kb of OG Bootstrap 🤦🏼 I guess I should have just deleted this repository and started from scratch lol.

**Comment by xezian** [comment]
Great suggestions, I'll be following up with all of them.

I'm sure there is a right way to customize bootstrap color variables only, and there's probably still a bunch of extra stuff in here, particularly in the `_variables.scss` file. I also like the suggestion of backporting a 1.3.x version with the cascade fix for text colors.

Working on these things now. Thanks!

**Comment by brxck** [comment]
For sure. I should also point out Bootstrap has customization docs: https://getbootstrap.com/docs/5.0/customize/overview/

**Comment by xezian** [comment]
- Made a new public s3 bucket to upload css to in publish action (https://fnsv-public-assets.s3.us-west-2.amazonaws.com/bootstrap.css) and updated demo page to use this instead.
- Edited `_colors.scss` to only customize $theme_color classes if the defaults weren't right (example bg- classes for `primary-` colors default to a dark text color.
- Added outline buttons for Brand colors, customized solid buttons to lighten/darken on hover appropriately 
- Extended demo page to include examples of `transparent-` classes, and Grayscale.
	- Added `river` to the correct section (was missing and mis-named in theme colors)

**Comment by xezian** [comment]
Going to make a branch of main now in which to update the class generation logic only, to publish a back ported optimization compatible with existing apps

**Comment by brxck** [comment]
Nice. This all sounds good, but why create a new bucket when an assets bucket, with CloudFront CDN, already exists? There's already a bunch of buckets for us & systems to keep track of.

**Comment by xezian** [comment]
> ...when an assets bucket, with CloudFront CDN, already exists?

I thought that was the case... but I couldn't figure out which bucket it is. Do you know the name?

**Comment by xezian** [comment]
Oh I guess it's `fastdev`, just found by looking in CloudFront

**Comment by brxck** [comment]
Yeah, it's poorly named.

**Comment by brxck** [comment]
We can't just replace that file with a new version as it's currently [in use.](https://github.com/search?q=org%3Auarizona-fnsv+https%3A%2F%2Fassets.cdn.fso.arizona.edu%2Ffso-bootstrap%2F&type=code)

**Comment by xezian** [comment]
OK I removed the errant bucket, and changed the aws command to 

`aws s3 sync dist s3://fastdev/assets/fso-bootstrap/@latest`

**Review by brxck — APPROVED** [review]

**Pull request merged**
